### ISSUE TITLE
Is it possible to make the listener as part of tomcat distribution?

### ISSUE THREAD

**Issue by stokito** [ascheman/tomcat-lifecyclelistener#2]
Hi and thank for your listener, you made a great work.
Could you publish your library to Maven Central or to push it into Tomcat itself?
That would be great.
Thank you.

**Comment by ascheman** [comment]
Thanks, you are welcome, @stokito!

Will publish it myself to Maven Central, cf. https://issues.sonatype.org/browse/OSSRH-41004

**Comment by ascheman** [comment]
@stokito: Finally managed to promate everything to the staging repository. According to the docs it show up in the next 10-120 minutes in Maven Central.
